server:
  port: 8081 # ya da bo?ta hangi port varsa

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/master
          jwk-set-uri: http://localhost:9090/realms/master/protocol/openid-connect/certs


jwt:
  auth:
    converter:
      resource-id: portal-client
      principle-attribute: username